/*
 * This file is generated by jOOQ.
 */
package de.kgalli.javalin_example.tables.records;


import de.kgalli.javalin_example.tables.Books;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BooksRecord extends TableRecordImpl<BooksRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = -730806933;

    /**
     * Setter for <code>public.books.title</code>.
     */
    public BooksRecord setTitle(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.books.title</code>.
     */
    public String getTitle() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.books.author</code>.
     */
    public BooksRecord setAuthor(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.books.author</code>.
     */
    public String getAuthor() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.books.isbn</code>.
     */
    public BooksRecord setIsbn(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.books.isbn</code>.
     */
    public String getIsbn() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Books.BOOKS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Books.BOOKS.AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Books.BOOKS.ISBN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getIsbn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIsbn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BooksRecord value1(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BooksRecord value2(String value) {
        setAuthor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BooksRecord value3(String value) {
        setIsbn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BooksRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BooksRecord
     */
    public BooksRecord() {
        super(Books.BOOKS);
    }

    /**
     * Create a detached, initialised BooksRecord
     */
    public BooksRecord(String title, String author, String isbn) {
        super(Books.BOOKS);

        set(0, title);
        set(1, author);
        set(2, isbn);
    }
}
